GET http://localhost:3000/products?q

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Auriculares Inalámbricos",
    "description": "Auriculares con cancelación de ruido.",
    "price": 129.99,
    "stock": 200,
    "categories": [1]
}
###

PATCH http://localhost:3000/products/2
Content-Type: application/json


    {
  "name": "Cafetera Programable Digital",
  "description": "Cafetera de goteo con capacidad para 12 tazas, programable 24 horas, con función de mantener caliente y filtro permanente lavable. Ideal para el hogar o la oficina.",
  "price": 79.99,
  "stock": 120,
  "category": [
    2,  
    21  
  ]
}


###
DELETE http://localhost:3000/products/4
